version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: postgres-ura-db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5433:5432"
    networks:
      - ura-network
    volumes:
      - ./db-data:/var/lib/postgresql/data
      - ./init_db/setup.sql:/docker-entrypoint-initdb.d/setup.sql

networks:
  ura-network:
    driver: bridge

# volumes:
#   pgdata: