name: ura-pipeline
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.11.7
  - pip=23.3.2
  - pip:
      - pandas==2.1.4
      - numpy==1.26.1
      - python-dotenv==1.0.0
      - psycopg2==2.9.9
      - scikit-learn==1.5.1
      - requests==2.31.0
      - SQLAlchemy==2.0.25
      - psycopg2-binary==2.9.9
      - PyYAML==6.0.1
      - ipykernel==6.25.0
      - nbformat==5.9.2
      - ipywidgets==8.1.1
      - seaborn==0.13.0
      - matplotlib==3.8.3
      - pytest==7.4.0