ura_api:
  endpoint: "https://www.ura.gov.sg/uraDataService/invokeUraDS?service=PMI_Resi_Transaction&batch="
  user_agent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36"
  verify_ssl: true
database:
  host: "localhost" # Default host; can be overridden by the environment variable POSTGRES_HOST
  port: 5433 # Default port; can be overridden by the environment variable POSTGRES_PORT
  name: "property_transactions_db" # Default database name; can be overridden by the environment variable POSTGRES_DB
  projects_table_query: "SELECT * FROM projects;"
  transactions_table_query: "SELECT * FROM private_property_transactions;"

data:
  data_path: "data"
  impute_cols:
    - "x_coordinate"
    - "y_coordinate"
  KNNIMPUTER: 3
  merge_strategy: "left"
  foreign_key: "project_id"
  primary_key: "id"
  property:
    column_name: "property_type"
    filter_property_type: "Executive Condominium"
  target_col: "price"
  drop_cols:
    - "project_id"
    - "tenure"
    - "street"
    - "nett_price"
    - "transaction_date"
    - "no_of_units"
    - "floor_range"
    - "property_type"
    - "project_name"
    - "type_of_area"

batches:
  range: [1, 4]
